### ISSUE TITLE
Fill out Section 3: User Study (20 Points)

### ISSUE THREAD

**Issue by Spike450x** [Spike450x/StarvingKnights_Application_Design#4]
### TASK INSTRUCTIONS ### 

Go to Section 3 of the [PD-01-ProjDlvrbl](https://docs.google.com/document/d/1lApO9XzSden0_rGr5w3xtfdCWBTg-d8C/edit?usp=sharing&ouid=100629307032256904247&rtpof=true&sd=true) and fill out each subsection.

### Description

A key component of user-centered design is gaining a deep understanding of your end user before you begin designing your technology solution. Make sure this section focuses on the users’ needs, not your app features. Be willing to adjust based on the feedback you get from your users.

### Subsection Checklist

- [x] User Classes

Often, one app has multiple interfaces for different users.  For example, an e-commerce app would have an interface for the business owners to maintain inventory and for customers who make purchases. List all of the main users of your app here that may require different interfaces for using your app. Clarify which user you will be focusing on when developing your prototype. You should interview at least one person who comes from each of these user classes for your user study.

- [ ] Stakeholder Analysis

Identify all (i.e., brainstorm an exhaustive list) of the potential stakeholders associated with your app the people who will use it, invest in it, benefit from it, or may even harmed by it. These are the people who will have influence over whether your app is ultimately a success or a failure. Describe each of their roles associated with your app and why they are stakeholders. I suggest that you represent this visually (e.g., Microsoft Smart Art graphic). These are also people you may consider interviewing for your user study.

- [ ] Recruitment

As part of this assignment, you will conduct five semi-structured interviews. Describe how you went about recruiting the participants for your user study here. 

- [x] Semi-Structured Interview Questions**

Provide a list of approximately 15 interview questions that you will ask/asked your users. Make sure to follow the guidelines provided in class, such as not leading your users will bias questions or focusing too much on the features or technology of your app. For each question, explain your goal for asking the question (e.g., to determine that the user is part of my target audience, to understand my user’s needs, etc.). Hint: If the answer to your question isn’t useful in designing your app, you may consid er asking a better question.

- [ ] Summary of Results

For each question asked in the semi-structured interview, summarize the responses across all of your users. Please do NOT just report the raw data from users. Focus on when your users agree or disagree with one another. For example, you could say something like “four out of five of our target users felt that xyz was a big challenge for them.  However, one user said that ‘direct quote here,’ showing that this was not a problem for them.” Don’t tie these results to implications for the design of your app yet; you should do that in the “Implications for Design” section below.

- [ ] Persona Development

Based on your insights from your interviews, create two detailed personas of typical users of your app. Try to make these personas different from one another, realistic, and not too stereotypical. Illustrate how these two personas will use your app. Highlight some of the challenges they may have (e.g., accessibility issues, special considerations). See the recorded lecture on personas and Google to make sure your personas are high quality. For each personas (like in the recorded lecture), provide detailed bullet points of key design implications associated with that type of user.

- [ ] Implications for Design

This step is critical and very difficult! Describe what you learned from your user study (stakeholder analysis, interviews, personas, etc.) that will directly influence your design. Compare the different user perspectives and report useful insights that you gleaned from the data. Reference your personas and use direct quotes from your user study to illustrate your findings.

For instance, are there any unique differences between users that you have to take into account? Are there any challenges that you will have to address in your design due to the different types of users What other implications can be made from the user profiles and other data you gathered? Highlight interesting insights that emerged from your data, especially those that you did not anticipate before talking to potential users. 

In order to identify key themes from your user data, you may consider brainstorming with your team to create an Affinity Diagram (See: http://infodesign.com.au/usabilityresources/affinitydiagramming/). This will help you group like ideas together to better understand all of the data you have collected.

Come up with at least five main design implications for your app. Describe each in detail and back up your design implications with evidence.
